AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
RSpec/ExampleLength:
  CountAsOne: ['array', 'heredoc']
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/StubbedMock:
  Enabled: false
Style/Documentation:
  Enabled: false
require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rspec
