AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
Style/Documentation:
  Enabled: false
require:
  - rubocop-performance
