name: Performance
on:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler-cache: true
      - run:  bundle exec bin/performance_local
